sudo apt -y install apt-transport-https
sudo apt -y install base-passwd
sudo apt -y install bash
sudo apt -y install bsdutils
sudo apt -y install ca-certificates
sudo apt -y install code
sudo apt -y install dash
sudo apt -y install diffutils
sudo apt -y install distro-info
sudo apt -y install exfatprogs
sudo apt -y install filelight
sudo apt -y install findutils
sudo apt -y install flatpak
sudo apt -y install gnupg
sudo apt -y install grep
sudo apt -y install grub-efi-amd64-signed
sudo apt -y install grub-efi-ia32-bin
sudo apt -y install gzip
sudo apt -y install hostname
sudo apt -y install init
sudo apt -y install krename
sudo apt -y install libdebconfclient0
sudo apt -y install linux-generic
sudo apt -y install linux-generic-hwe-22.04
sudo apt -y install login
sudo apt -y install lsb-release
sudo apt -y install ncdu
sudo apt -y install ncurses-base
sudo apt -y install ncurses-bin
sudo apt -y install neon-desktop
sudo apt -y install partitionmanager
sudo apt -y install plasma-discover-backend-flatpak
sudo apt -y install python3-distutils
sudo apt -y install shim-signed
sudo apt -y install sshs
sudo apt -y install sysvinit-utils
sudo apt -y install tree
sudo apt -y install wbritish
sudo apt -y install wezterm
sudo apt -y install syncthing # needs additional setup
sudo apt -y install tailscale # needs additional setup
sudo apt -y install tailscale-archive-keyring
