#!/bin/bash

sudo apt install -y apt-transport-https
sudo apt install -y base-passwd
sudo apt install -y bash
sudo apt install -y bsdutils
sudo apt install -y ca-certificates
sudo apt install -y code
sudo apt install -y curl
sudo apt install -y dash
sudo apt install -y diffutils
sudo apt install -y distro-info
sudo apt install -y exfatprogs
sudo apt install -y filelight
sudo apt install -y findutils
sudo apt install -y flatpak
sudo apt install -y gnupg
sudo apt install -y grep
sudo apt install -y grub-efi-amd64-signed
sudo apt install -y grub-efi-ia32-bin
sudo apt install -y gzip
sudo apt install -y hostname
sudo apt install -y init
sudo apt install -y krename
sudo apt install -y libdebconfclient0
sudo apt install -y linux-generic
sudo apt install -y linux-generic-hwe-22.04
sudo apt install -y login
sudo apt install -y lsb-release
sudo apt install -y ncdu
sudo apt install -y ncurses-base
sudo apt install -y ncurses-bin
sudo apt install -y neon-desktop
sudo apt install -y partitionmanager
sudo apt install -y plasma-discover-backend-flatpak
sudo apt install -y python3-distutils
sudo apt install -y shim-signed
sudo apt install -y sysvinit-utils
sudo apt install -y tree
sudo apt install -y wbritish